version: 1
formatters:
  simple:
    class: logging.Formatter
    format: "%(levelname)s %(message)s"
    datefmt: "%d %b %Y %H:%M:%S"
handlers:
  all_handler:
    class: logging.FileHandler
    filename: stackoverflow_analytics.log
    level: DEBUG
    formatter: simple
  warn_handler:
    class: logging.FileHandler
    filename: stackoverflow_analytics.warn
    level: WARNING
    formatter: simple
loggers:
  application_logger:
    level: DEBUG
    handlers: [all_handler, warn_handler]
